import axios from 'axios';
const config = {
    withCredentials: true,
    headers: {
        'Content-Type': 'application/json'
    }
};

const base = '/api/v1/user';
export default class AuthService {
    /**
     *
     * @param {string} email user email
     * @param {string} password user password
     * @param {string} firstName first name
     * @param {string} lastName last name
     * @param {string[]} classes array of classes
     */
    signup(email, password, firstName, lastName, classes) {
        return new Promise((resolve, reject) => {
            const data = {
                email: email,
                password: password,
                firstName: firstName,
                lastName: lastName,
                classes: classes
            };
            const url = base + '/signup';
            axios
                .post(url, data, config)
                .then(res => {
                    resolve(res);
                    if (res.status == 200) {
                        resolve('Account created. Please verify your email.');
                    }
                    // Uncaught error
                    reject('There was an error.');
                })
                .catch(err => {
                    if (err.response.status == 409) {
                        reject('This email is already being used.');
                    }
                    if (err.response.status == 500) {
                        reject('There was an error saving your account.');
                    }
                    reject('There was an error.');
                });
        });
    }
    /**
     *
     * @param {string} email User email
     * @param {string} password User password
     */
    login(email, password) {
        return new Promise((resolve, reject) => {
            let config = {
                withCredentials: true,
                headers: {
                    'Content-Type': 'application/json'
                }
            };
            let data = {
                email: email,
                password: password
            };
            const url = base + '/login';
            axios
                .post(url, data, config)
                .then(res => {
                    if (res.status == 200) {
                        // logged in
                        resolve('Logged in.');
                    } else {
                        // no clue
                        reject('There was an erorr.');
                    }
                })
                .catch(err => {
                    if (err.response.status == 400) {
                        // Incorrect password
                        reject('Incorrect password');
                    }
                    if (err.response.status == 404) {
                        // No user
                        reject('User does not exist.');
                    }
                    // catch all errors
                    reject('There was an error.');
                });
        });
    }
    logout() {
        return new Promise((resolve, reject) => {
            const url = base + '/logout';
            axios
                .get(url)
                .then(res => {
                    resolve(res);
                })
                .catch(err => {
                    reject(err);
                });
        });
    }
    isAuth() {
        return new Promise((resolve, reject) => {
            const url = base + '/current';
            axios
                .get(url)
                .then(res => {
                    if (res.data.user) {
                        resolve(res.data.user);
                    }
                    reject('Not logged in.');
                })
                .catch(() => {
                    reject('There was an error.');
                });
        });
    }
    verify(code) {
        return new Promise((resolve, reject) => {
            const url = base + '/signup/' + code;
            axios
                .get(url)
                .then(res => {
                    resolve(res);
                })
                .catch(err => {
                    reject(err);
                });
        });
    }
    /**
     *
     * @param {string} token Token that was generated by the server
     * @param {string} newPassword Password that the user wants to change to
     * @param {string} confirmPassword Password that the user wants to change to
     */
    reset(token, newPassword, confirmPassword) {
        return new Promise((resolve, reject) => {
            if (newPassword !== confirmPassword) {
                reject('Passwords must match.');
            } else {
                const url = base + '/reset-password/' + token;
                const data = {
                    newPassword: newPassword
                };
                axios
                    .post(url, data, config)
                    .then(() => {
                        resolve('Password Changed.');
                    })
                    .catch(err => {
                        if (err.response.status == 500) {
                            reject('There was an error.');
                        } else if (err.response.status == 401) {
                            reject('Invalid token.');
                        }
                        reject('There was an error.');
                    });
            }
        });
    }

    /**
     *
     * @param {string} email Email of user
     */
    requestReset(email) {
        return new Promise((resolve, reject) => {
            const url = base + '/reset-password';
            const data = {
                email: email
            };
            axios
                .post(url, data, config)
                .then(res => {
                    console.log(res);
                    resolve(
                        'Password reset requested. Please check your email.'
                    );
                })
                .catch(err => {
                    if (err.response.status == 404) {
                        reject('Did not find user with that email.');
                    } else if (err.response.status == 400) {
                        reject('That is not a valid email.');
                    }
                    reject('There was an error.');
                });
        });
    }
}
